name: Ubuntu

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Installing dependencies
      run: yarn install
    - name: Build
      run: yarn deploy 
    - name: Publish binaries
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ov-webmixer-*
        tag: "Release"
        overwrite: true
        file_glob: true
